SAAS-508 add reset password link in SignIn
percona-platform/grafana pull request #135
Opened 2021-04-30 17:02 UTC by nicolalamacchia

<img width="426" alt="Untitled2" src="https://user-images.githubusercontent.com/2530868/116728742-90b0a500-a9e6-11eb-892e-5e56ca6763f2.png">
<img width="428" alt="Untitled" src="https://user-images.githubusercontent.com/2530868/116728752-94dcc280-a9e6-11eb-9b48-60cd9a933f0d.png">

2021-04-30 17:59 UTC, atymchuk requested changes

2021-04-30 17:59 UTC, atymchuk commented on public/app/percona/settings/components/PlatformLogin/PlatformLogin.constants.ts
> +  process.env.NODE_ENV !== 'production'
Isn't it the opposite? 
```suggestion
  process.env.NODE_ENV === 'production'
```

2021-05-03 10:31 UTC, fabio-silva approved these changes
Nothing from me except what Alex already mentioned

2021-05-03 11:06 UTC, atymchuk approved these changes

2021-05-03 14:53 UTC, fabio-silva approved these changes

2021-05-03 17:18 UTC, tiagomotasantos approved these changes

2021-05-04 08:51 UTC, merged