PMM-8166: scheduled backups list
percona-platform/grafana pull request #167
Opened 2021-06-14 10:28 UTC by fabio-silva

**What this PR does / why we need it**: https://jira.percona.com/browse/PMM-8166

**Which issue(s) this PR fixes**: Lists scheduled backups

2021-06-14 18:16 UTC, nicolalamacchia submitted a review, later dismissed

2021-06-17 10:16 UTC, tiagomotasantos submitted a review, later dismissed

2021-06-25 14:27 UTC, nicolalamacchia requested changes

2021-06-25 14:27 UTC, nicolalamacchia commented on public/app/percona/backup/components/AddBackupModal/AddBackupModal.tsx
> +            {/* {!scheduleMode && <RetryModeSelector disabled retryMode={RetryMode.MANUAL} />} */}
Please remove commented code

2021-06-25 14:27 UTC, nicolalamacchia commented on public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.tsx
> +      } = backup;
should this be in the `try` block?

2021-06-25 14:27 UTC, nicolalamacchia commented on public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.types.ts
> +  // retry_times: number;
Remove commented code

2021-06-25 14:27 UTC, nicolalamacchia commented on public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.tsx
> +      const { serviceId, locationId, cronExpression, name, description, enabled } = backup;
Move this outside of `try`

2021-06-25 14:27 UTC, nicolalamacchia commented on public/app/percona/backup/components/ScheduledBackups/ScheduledBackupsActions/ScheduledBackupsActions.tsx
> +          <Switch value={!!backup.enabled} onClick={handleToggle} data-qa="toggle-scheduled-backpup" />
`backup.enabled` shouldn't need to be casted to boolean

2021-07-05 14:09 UTC, nicolalamacchia approved these changes

2021-07-05 16:13 UTC, nicolalamacchia submitted a review, later dismissed

2021-07-08 09:40 UTC, closed without merging