PMM-8547: fix error message-text wrapping
percona-platform/grafana pull request #252
Opened 2021-10-12 06:24 UTC by ritbl

[Jira ticket](https://jira.percona.com/browse/PMM-8547)

2021-10-17 18:19 UTC, ritbl commented
@atymchuk done

2021-10-18 09:50 UTC, tiagomotasantos requested changes

2021-10-18 09:50 UTC, tiagomotasantos commented on public/app/percona/settings/components/MetricsResolution/MetricsResolution.styles.ts
> +    white-space: nowrap;
Any reason for `overflow`? I think `white-space` is enough.

2021-10-20 10:24 UTC, tiagomotasantos approved these changes

2021-11-04 10:34 UTC, merged