PMM-7527 UI improvs to IA
percona-platform/grafana pull request #265
Opened 2021-11-08 16:06 UTC by fabio-silva

**What this PR does / why we need it**: 
Adds improvements to IA's UI, namely:
- Bigger 'delete' icon;
- Bigger up/down arrow icons;
- Tooltips for actions;

**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7527

2021-11-08 18:46 UTC, tiagomotasantos requested changes

2021-11-08 18:46 UTC, tiagomotasantos commented on public/app/percona/backup/components/ScheduledBackups/ScheduledBackupsActions/ScheduledBackupsActions.tsx
> +            <IconButton data-testid="copy-alert-scheduled-backup-button" name="copy" onClick={handleCopy} />
```suggestion
            <IconButton data-testid="copy-scheduled-backup-button" name="copy" onClick={handleCopy} />
```

2021-11-08 19:52 UTC, fabio-silva commented on public/app/percona/backup/components/ScheduledBackups/ScheduledBackupsActions/ScheduledBackupsActions.tsx
> +            <IconButton data-testid="copy-alert-scheduled-backup-button" name="copy" onClick={handleCopy} />
well spotted !

2021-11-09 12:20 UTC, tiagomotasantos approved these changes

2021-11-10 19:48 UTC, merged