PMM-9152: update rule fields after API change
percona-platform/grafana pull request #271
Opened 2021-11-16 15:31 UTC by fabio-silva

**What this PR does / why we need it**: most fields from a rule's template were moved and renamed.

**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9152

2021-11-23 08:09 UTC, solovevayaroslavna approved these changes

2021-11-29 15:22 UTC, tiagomotasantos requested changes

2021-12-09 15:38 UTC, fabio-silva commented on public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.tsx
> +                        if (type === TemplateParamType.FLOAT && float?.default !== undefined) {
`0` as default is a possibility, so I think we shouldn't make it that way :S

2021-12-15 09:35 UTC, tiagomotasantos approved these changes

2021-12-15 18:39 UTC, merged