PMM-8282-add-tooltips-to-tls-options: add tooltips
percona-platform/grafana pull request #276
Opened 2021-11-22 05:56 UTC by solovevayaroslavna

**What this PR does / why we need it**:
It might not be clear to user which file goes to which form
![image](https://user-images.githubusercontent.com/90199600/142808099-8e4f1a5b-2437-4985-aab5-35d331f0c79e.png)
**Which issue(s) this PR fixes**:
https://jira.percona.com/browse/PMM-8282

2021-11-22 10:11 UTC, fabio-silva requested changes
@solovevayaroslavna we now have `tooltipText` and others as props for our inputs. Please check `AddAlertRuleModal.tsx` to see it working.

2021-11-22 12:57 UTC, fabio-silva approved these changes

2021-11-22 19:02 UTC, tiagomotasantos requested changes

2021-11-22 19:02 UTC, tiagomotasantos commented on public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.messages.ts
> +        tlsCA: 'Provide the CA certificate (example: ca.pem)',
Here's an example of a better description: 
```suggestion
        tlsCA: 'Content of the trusted Certificate Authority (CA) file used to sign client certificates',
```

Pls apply the same principle to the other tooltips. All the information required is in the following doc: https://www.postgresql.org/docs/9.1/ssl-tcp.html

2021-11-23 14:37 UTC, tiagomotasantos requested changes
Only saw now that they don't use capital letters for CAs (my bad sorry). Other than that very good job with updating the tooltips 🚀

2021-11-23 14:37 UTC, tiagomotasantos commented on public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.messages.ts
> +          'Content of the trusted client certificate file signed by one of the trusted Certificate Authority (CA)',
```suggestion
          'Content of the client certificate file signed by one of the trusted certificate authorities (CAs)',
```

2021-11-23 14:37 UTC, tiagomotasantos commented on public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.messages.ts
> +        tlsCA: 'Content of the trusted Certificate Authority (CA) file used to sign client certificates',
```suggestion
        tlsCA: 'Content of the trusted certificate authority (CA) file used to sign client certificates',
```

2021-11-23 16:06 UTC, tiagomotasantos approved these changes

2021-11-30 06:20 UTC, merged