Pmm 9526 migrate enzyme to rtl
percona-platform/grafana pull request #378
Opened 2022-03-28 04:58 UTC by solovevayaroslavna

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
https://jira.percona.com/browse/PMM-9526

2022-04-05 20:04 UTC, fabio-silva requested changes

2022-04-06 06:59 UTC, solovevayaroslavna commented on public/app/percona/backup/components/AddBackupModal/RetryModeSelector/RetryModeSelector.test.tsx
> +    expect(screen.getByTestId('retryTimes-number-input')).toHaveProperty('disabled', false);
yes, thank you for the remark! I did not immediately find out about this method and did not rewrite it everywhere, I will correct it!

2022-04-12 09:31 UTC, fabio-silva commented
@solovevayaroslavna I can still see change on yarn.lock. Have we reverted it?

2022-04-12 09:42 UTC, solovevayaroslavna commented
@fabio-silva I accidentally commented it out again during edits with disabled, so I brought it back to the main state again.

2022-04-12 09:43 UTC, solovevayaroslavna commented
@fabio-silva If you look at the general PR, then it has already been fixed there

2022-04-12 09:53 UTC, fabio-silva approved these changes

2022-04-14 13:56 UTC, merged