PMM-9363 logout after disconnecting from Portal
percona-platform/grafana pull request #405
Opened 2022-04-19 10:24 UTC by fabio-silva

**What this PR does / why we need it**: Logout user after disconnecting from Portal, via a modal

**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9363

2022-04-19 13:35 UTC, filipmikes1 submitted a review, later dismissed

2022-04-21 09:40 UTC, solovevayaroslavna requested changes
Are we not going to add a unit test to check the confirmationModal?

2022-04-21 10:39 UTC, fabio-silva commented
> Are we not going to add a unit test to check the confirmationModal?

Yep, good one 👍

2022-04-25 03:07 UTC, solovevayaroslavna approved these changes

2022-04-29 09:34 UTC, nicolalamacchia approved these changes

2022-04-29 09:53 UTC, merged