PMM-9885-advanced-settings-read-more-links-fix: new links
percona-platform/grafana pull request #408
Opened 2022-04-24 07:15 UTC by solovevayaroslavna

https://jira.percona.com/browse/PMM-9885

2022-04-26 09:49 UTC, denisok submitted a review, later dismissed

2022-04-27 09:25 UTC, fabio-silva approved these changes

2022-04-27 11:47 UTC, denisok requested changes
per new findings this link is incorrect, please see jira

2022-04-27 11:51 UTC, denisok approved these changes

2022-04-27 11:51 UTC, denisok commented
> per new findings this link is incorrect, please see jira

oops, looked into the wrong line. all good

2022-04-27 15:12 UTC, merged