PMM-10092 Add support for recursive expanded menu
percona-platform/grafana pull request #484
Opened 2022-08-17 13:46 UTC by matejkubinec

https://jira.percona.com/browse/PMM-10092

2022-09-05 22:23 UTC, fabio-silva requested changes
Very good job @matejkubinec 🚀 
Just some fome few nits, but it seems working fine !

2022-09-05 22:23 UTC, fabio-silva commented on packages/grafana-ui/src/components/Icon/utils.ts
> +  'percona-database-haproxy',
let's add these to `iconBundle.ts`, along with all others 👍

2022-09-05 22:23 UTC, fabio-silva commented on public/app/core/components/NavBar/NavBar.tsx
> +      if (alertingEnabled) {
the indentation seems wrong here

2022-09-05 22:23 UTC, fabio-silva commented on public/app/core/components/NavBar/NavBarMenu.tsx
> +              {!isRoot && <span className={styles.collapsibleIcon}>{getLinkIcon(link, isRoot ? 'xl' : 'sm')}</span>}
the span will only show if `!isRoot`, so I believe that `isRoot ? 'xl' : 'sm'` condition is redundant

2022-09-06 08:54 UTC, fabio-silva approved these changes

2022-09-07 08:52 UTC, solovevayaroslavna approved these changes

2022-09-08 21:36 UTC, merged