PMM-10503 backup modal
percona-platform/grafana pull request #486
Opened 2022-08-19 13:54 UTC by fabio-silva

**What this PR does / why we need it**: Adds a checkbox to backup modal to change between on-demand / scheduled view

**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-10503

2022-08-23 14:53 UTC, filipmikes1 requested changes

2022-08-24 21:30 UTC, fabio-silva commented on public/app/percona/backup/components/AddBackupModal/AddBackupModal.utils.ts
> +
Good one!

2022-08-24 21:30 UTC, fabio-silva commented on public/app/percona/backup/components/AddBackupModal/AddBackupModal.tsx
> +                      On Demand
👍

2022-08-24 21:30 UTC, fabio-silva commented on public/app/percona/backup/components/AddBackupModal/AddBackupModal.tsx
> +                      Schedule Backup
👍

2022-08-25 08:13 UTC, filipmikes1 approved these changes

2022-09-06 13:47 UTC, filipmikes1 submitted a review, later dismissed

2022-09-07 09:07 UTC, solovevayaroslavna submitted a review, later dismissed

2022-09-27 14:40 UTC, filipmikes1 approved these changes

2022-11-15 08:03 UTC, solovevayaroslavna commented
Is it relevant? Can we close it? I have to much old PRs in my review list

2022-12-05 10:53 UTC, closed without merging