PMM-10579 Navigation - Check services
percona-platform/grafana pull request #517
Opened 2022-09-28 09:53 UTC by matejkubinec

**What this PR does / why we need it**:

Filters menu items based on active services.

**Which issue(s) this PR fixes**:

Fixes PMM-10579

**Special notes for your reviewer**:

Currently adding a service by CLI will not update the state on the FE, either polling on some kind of websocket connection will need to be added to update the FEs state.

2022-09-30 19:40 UTC, fabio-silva requested changes

2022-10-05 14:44 UTC, matejkubinec commented on public/app/percona/inventory/Tabs/Services.tsx
> +        const successfullyDeleted = await dispatch(removeServicesAction({ services: params })).unwrap();
It shouldn't fail, as the promises for the api remove requests are process and errors from them are `processPromiseResults` function.

2022-10-05 14:45 UTC, matejkubinec commented on public/app/percona/shared/core/reducers/services/services.ts
> +    thunkAPI.dispatch(setLoading(false));
Had to rewrite the reducer a bit to add the new endpoint for checking active service types. I could use there the `createAsyncSlice` util, but I've added handling of loading state through the extra reducers builder.

2022-10-05 19:33 UTC, fabio-silva submitted a review, later dismissed

2022-10-11 11:28 UTC, fabio-silva submitted a review, later dismissed

2022-10-19 10:26 UTC, fabio-silva approved these changes

2022-10-20 08:47 UTC, merged