PMM-10963 Access Role Management
percona-platform/grafana pull request #577
Opened 2022-12-06 14:46 UTC by matejkubinec

**What this PR does / why we need it**:

Adds pages for managing access roles - create, edit, delete. Adds new column to users table for updating users access role.

**Which issue(s) this PR fixes**:

PMM-10963

**Screenshots:**

Configuration menu:
![image](https://user-images.githubusercontent.com/32638572/210762986-ef9179d0-8535-4158-bff3-de203aa04aa0.png)
![image](https://user-images.githubusercontent.com/32638572/210765694-c3920b5f-78b3-4fad-b6ef-3499750258dd.png)

Add/Edit Role:
![image](https://user-images.githubusercontent.com/32638572/210765257-2ba3027b-dd6b-44be-ba4d-13ae869c4d64.png)
![image](https://user-images.githubusercontent.com/32638572/210765966-3ce88c1f-a5b4-403a-94cf-8b3617b03a54.png)

Access Roles tab:
![image](https://user-images.githubusercontent.com/32638572/210765428-26222a37-13b4-446b-b37e-598d9337f432.png)

Users table:
![image](https://user-images.githubusercontent.com/32638572/210765617-ade095fa-b35a-4edd-a04f-479cff8654d6.png)

2023-01-05 10:43 UTC, fabio-silva commented
@matejkubinec Can you just add some screenshots so that we can see how it looks like?

2023-01-05 11:05 UTC, matejkubinec commented
> @matejkubinec Can you just add some screenshots so that we can see how it looks like?

Screenshots added.

2023-01-07 02:04 UTC, fabio-silva requested changes
Some small questions, but wonderful job 💪 💪

2023-01-09 07:23 UTC, matejkubinec commented on public/app/percona/rbac/AccessRoleCell/AccessRoleCell.tsx
> +    const ids = roleIds.map((v) => Number(v.value));
Checked, it will always be a defined number here, refactored.

2023-01-09 07:24 UTC, matejkubinec commented on public/app/percona/rbac/AccessRolesEnabledCheck/AccessRolesEnabledCheck.tsx
> +export default AccessRolesEnabledCheck;
Doing it this way also prevents the mount effect from being called (there's no reason to hit the api if the access roles are not enabled).

I think doing it this way it's easier that to do conditional checking in each of the components useEffects.

2023-01-09 07:25 UTC, matejkubinec commented on public/app/percona/rbac/AccessRolesEnabledCheck/AccessRolesEnabledCheck.tsx
> +export default AccessRolesEnabledCheck;
Also, I doesn't make sense to do it in the parent component as it's a Grafana page, and it'll be a bit less maintenance this way.

2023-01-09 07:26 UTC, matejkubinec commented on public/app/percona/rbac/AddEditRole/EditRolePage/EditRolePage.tsx
> +        const role = await RolesService.get(Number(id));
Yes, this will always be string as it's a route parameter, refactored to use `parseInt`.

2023-01-09 07:26 UTC, matejkubinec commented on public/app/percona/rbac/AddEditRole/components/LabelsField/components/LabelsBuilder/LabelsBuilder.styles.ts
> +    & > div:nth-child(1) label {
Fixed.

2023-01-09 18:21 UTC, filipmikes1 commented on public/app/percona/rbac/AccessRoles/components/OptionsCell/OptionsCell.tsx
> +        <IconButton ariaLabel="Open role options" name="ellipsis-v" />
Just a small thing, since you are using aria label it would be nice to have it in separate messages file as well.

2023-01-17 01:22 UTC, fabio-silva commented on public/app/percona/rbac/AccessRolesEnabledCheck/AccessRolesEnabledCheck.tsx
> +export default AccessRolesEnabledCheck;
Good points 👍

2023-01-17 01:23 UTC, fabio-silva submitted a review, later dismissed

2023-01-24 14:26 UTC, filipmikes1 submitted a review, later dismissed

2023-02-02 09:42 UTC, fabio-silva submitted a review, later dismissed

2023-02-06 13:20 UTC, fabio-silva submitted a review, later dismissed

2023-02-08 09:06 UTC, fabio-silva approved these changes

2023-02-08 11:04 UTC, fabio-silva approved these changes

2023-02-08 13:01 UTC, merged