PMM-6695 grafana v7.3.7
percona-platform/grafana pull request #60
Opened 2021-02-08 19:10 UTC by lunaticusgreen

**What this PR does / why we need it**: Upgrades grafana to version 7.3.7

**Which issue(s) this PR fixes**: PMM-6695

Fixes #

**Special notes for your reviewer**:

2021-02-12 13:01 UTC, atymchuk requested changes

2021-02-15 13:11 UTC, lunaticusgreen commented on packages/grafana-ui/src/components/Slider/Slider.test.tsx
> +xdescribe('Slider', () => {
Thanks for the comment, I'll add it, the problem is slider tests started to fail without any visible changes of the slider, commented on it just to check the build working and not to block QA

2021-02-15 13:22 UTC, nicolalamacchia commented
Is `master` the right branch this PR should be merged to?

2021-02-16 10:34 UTC, lunaticusgreen commented on public/app/features/integrated-alerting/components/AlertRules/AlertRules.utils.ts
> +  const unit = paramUnit && AlertRulesListPayloadTemplateParamUnits[paramUnit];
Thanks, fixed!

2021-02-16 10:35 UTC, lunaticusgreen commented on public/app/features/integrated-alerting/components/AlertRuleTemplate/AddAlertRuleTemplateModal/AddAlertRuleTemplateModal.tsx
> +                  // TODO: fix LoaderButton types
Thanks, it was fixed in the latest version of platform package so this comment is no longer required

2021-02-16 10:39 UTC, lunaticusgreen commented on packages/grafana-ui/src/components/Slider/Slider.test.tsx
> +xdescribe('Slider', () => {
It seems like it just something strange with Slider on grafana side, didn't want to spend a lot of time to investigate it if you don't mind I'll check changes of Slider component tests when will be working on an upgrade to grafana 7.4

2021-02-16 17:58 UTC, fabio-silva submitted a review, later dismissed

2021-02-18 07:14 UTC, atymchuk approved these changes

2021-02-18 07:17 UTC, merged