PMM-11113: new Portal connection layout
percona-platform/grafana pull request #603
Opened 2023-01-27 14:54 UTC by fabio-silva

**What this PR does / why we need it**: Changes the layout for the Portal connection from PMM

**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-11113

<img width="621" alt="Screenshot 2023-01-27 at 14 48 22" src="https://user-images.githubusercontent.com/4190654/215116249-bb2e3bee-ee27-4bf5-bc34-380744b9df4b.png">

2023-01-27 15:08 UTC, matejkubinec requested changes
Just really small nitpicks, otherwise looks great!

2023-01-27 15:08 UTC, matejkubinec commented on public/app/percona/settings/components/Platform/Connect/Connect.tsx
> +          <TextInputField name="pmmServerId" disabled label={Messages.pmmServerId} fieldClassName="my-class" />
What does the `fieldClassName="my-class"` mean here?

2023-01-27 15:08 UTC, matejkubinec commented on public/app/percona/settings/components/Platform/Connect/Connect.tsx
> +            placeholder="Token here..."
Placeholder could be added to messages.

2023-01-27 15:08 UTC, matejkubinec commented on public/app/percona/settings/components/Platform/Connect/Connect.tsx
> +              Get token
Button text could be added to messages.

2023-01-28 11:23 UTC, matejkubinec submitted a review, later dismissed

2023-02-06 11:53 UTC, filipmikes1 approved these changes

2023-02-06 12:14 UTC, merged