PMM-11962 filtering for services and nodes in inventory
percona-platform/grafana pull request #653
Opened 2023-04-14 13:37 UTC by filipmikes1

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
https://jira.percona.com/browse/PMM-11962

Fixes #

**Special notes for your reviewer**:

2023-04-20 11:16 UTC, fabio-silva requested changes

2023-04-20 11:16 UTC, fabio-silva commented on public/app/percona/inventory/Tabs/Agents.tsx
> +            // emptyMessageClassName={styles.emptyMessage}
if this not needed?

2023-04-20 11:16 UTC, fabio-silva commented on public/app/percona/inventory/Tabs/Nodes.tsx
> +        type: FilterFieldTypes.TEXT,
should this be text? I think the believe the type is an enum

2023-04-20 11:16 UTC, fabio-silva commented on public/app/percona/inventory/Tabs/Services.tsx
>              text={capitalizeText(value)}
Let's take the chance to fix something here:
```
text={value === ServiceStatus.NA ? ServiceStatus.NA : capitalizeText(value)}
```

2023-04-20 11:16 UTC, fabio-silva commented on public/app/percona/inventory/Tabs/Services.tsx
>              text={capitalizeText(value)}
Because it's showing as "N/a" right now

2023-04-27 14:29 UTC, filipmikes1 commented on public/app/percona/integrated-alerting/components/Table/Filter/Filter.utils.ts
> +  haystack.toString().toLowerCase().includes(needle.toLowerCase());
Because in runtime when value is number it will fail

2023-04-28 15:24 UTC, fabio-silva submitted a review, later dismissed

2023-05-11 13:09 UTC, fabio-silva approved these changes

2023-05-11 13:09 UTC, merged